# Майнор "Интеллектуальный анализ данных", Введение в Анализ данных (ВШЭ)
## Домашнее задание №1. <font color='red'>Авторское решение</font> 

__Дата выдачи__: 28.01.2016

__Дедлайн__: 23:59 10.01.2016

Задание состоит в том, чтобы дописать в этом ipython notebook тело для всех функций, чтобы они работали так, как указано в формулировке. 

### Не нужно создавать свои функции с другими названиями!
Точнее, ответ должна выдавать именно та функция, которая указана в задании. Промежуточные функции создавать, конечно, можно.

Готовый файл нужно переименовать в формате iad16\_SnapeS.ipynb (заменив фамилию «Snape» и первую букву имени «S» на свои) и прислать на [hse.minor.dm+16@gmail.com](hse.minor.dm+16@gmail.com), указав в теме «[HW1] SnapeS».

Мы настоятельно рекомендуем выполнять задание на своем компьютере. Для этого лучше всего создать отдельную папку, скопировать туда этот notebook, открыть консоль (например, в Windows8: Shift + правая кнопка мыши, выбрать "Открыть → Окно команд") и написать jupyter notebook. Тогда вы всегда будете знать, где находятся ваши файлы.

При выполнении на сервере не гарантируется его стабильная работа, и ваш код смогут видеть другие студенты. 

На всякий случай напоминаем, что списывать нехорошо. За это будет <s>выпорот</s> сурово наказан и тот, кто списал, и тот, кто у кого списали. Но надеемся, что таких случаев не будет

Если формулировка задания не ясна — пишите на почту курса или семинаристам лично. Мы с радостью поможем разобраться.

Непонятные термины рекомендуем гуглить :) 

А вот решения гуглить не рекомендуем: задания не очень сложные, и сделаны они в первую очередь для того, чтобы вы освоились с numpy и pandas. Без этого дальше изучать курс будет сложно.

__Каждое выполненное задание дает 1 балл.__

При решении задач нельзя пользоваться циклами и рекурсией.

In [1]:
import numpy as np

<font color='red'>Все задачи хорошо и красиво решаются чистым numpy или pandas, и это значительно __ускоряет__ вычисления (по сравнению с map, циклами и прочим чистым питоном). Пруф ниже :)</font> 

# во всех задачах запрещается использовать циклы и рекурсию!

__№1__.  Написать функцию, которая берет на вход прямоугольную матрицу $A$ размера m x n и превращает каждый ее столбец в дискретное распределение с помощью применения функции _softmax_:

$\text{softmax}(a_j) = \frac {\exp (a_j)}{\sum_i \exp(a_i)}$, где a --- столбец матрицы $A$.

Таким образом, в матрице, возвращенной функцией, сумма каждого столбца матрицы должна быть равна 1.

In [7]:
#Пример

Example
Input:
[[0 1]
 [1 2]]
Output:
[[ 0.26894142  0.26894142]
 [ 0.73105858  0.73105858]]


<font color='red'>Авторское решение:</font> 

In [8]:
def compute_softmax(A):
    expA = np.exp(A)   # вычислили экспоненту
    return expA / expA.sum(axis=0)[np.newaxis, :]  
    # с помощью newaxis оцень удобно нормировать матрицы (о newaxis см. доп. материал на github)

<font color='red'>compute_softmax принимает на вход __любую__ прямоугольную матрицу и возвращает ее в преобразованном виде. Проверим нашу функцию на данных из примера:</font> 

In [9]:
A = np.array([[0, 1], [1, 2]])
print compute_softmax(A)

[[ 0.26894142  0.26894142]
 [ 0.73105858  0.73105858]]


__№2__. Напишите функцию, принимающую на вход матрицу X и два массива i и j одинаковой длины n и возвращающую вектор np.array, состоящий из последовательности элементов [X[i[0], j[0]], X[i[1], j[1]], ..., X[i[n-1], j[n-1]]].

In [11]:
#Пример

Example
Input:
X = [[0 1]
 [1 2]]
i =  [0 0] j =  [0 1]
Output:
0 1


<font color='red'>Авторское решение:</font> 

In [11]:
def choose_elems(X, i, j):
    return X[i, j]   # просто задание на индексацию

<font color='red'>Тест:</font> 

In [16]:
print choose_elems(np.array([[0, 1], [1, 2]]), np.array([0, 0]), np.array([0, 1]))

[0 1]


<font color='red'>На примере этого задания давайте увидим, что решения с numpy __значительно__ быстрее решений на чистом python. Для этого воспользуемся magic-командой %timeit. Она запускает строчку кода много раз и усредняет время ее выполнения.
Сравним авторское решение с решением через map и через циклы.</font> 

In [17]:
def choose_elems2(X, i, j):
    # решение взято из работы анонимного студента
    arr = []
    np.array(map((lambda x: arr.append(X[i[x], j[x]])), np.arange(len(i))))
    return np.array(arr)
def choose_elems3(X, i, j):
    # наиболее интуитивное решение через циклы
    arr = []
    for ind in range(i.shape[0]):
        arr.append(X[i[ind], j[ind]])

In [26]:
X = np.random.rand(1000, 1000)   
i = np.random.randint(1000, size=500000) # Берем побольше данные
j = np.random.randint(1000, size=500000)
%timeit choose_elems(X, i, j)
%timeit choose_elems2(X, i, j)
%timeit choose_elems3(X, i, j)

10 loops, best of 3: 33.3 ms per loop
1 loops, best of 3: 987 ms per loop
1 loops, best of 3: 604 ms per loop


<font color='red'>Первое значительно быстрее двух других!!!</font> 

__№3__. Написать функцию, которая берет на вход матрицу A размера m x n, вектор b длины m и вектор c длины n и возвращает матрицу, составленную из блоков:

$\begin{pmatrix} A & b \\  c^T& 0 \end{pmatrix}$ = 

$\begin{pmatrix} a_{00} & a_{01} & \dots &a_{0,n-1} & b_0 \\ 
a_{10} & a_{11} & \dots &a_{1,n-1} & b_1 \\
 &&\dots& \\
a_{m-1,0} & a_{m-1,1} & \dots &a_{m-1,n-1} & b_{m-1} \\ 
c_0 & c_1 & \dots & c_{n-1 }& 0 \end{pmatrix}$


In [12]:
#Пример

Example
Input:
A = [[0 1]
 [1 2]]
b =  [8 9] c =  [7 3]
Output:
[[0 1 8]
 [1 2 9]
 [7 3 0]]


<font color='red'>Авторское решение:</font> 

In [37]:
def construct_matrix(A, b, c):
    # здесь мы очень хотели, чтобы вы пользовались функциями hstack и vstack :)
    # вы ими и пользовались, молодцы :)
    Ab = np.hstack((A, b[:, np.newaxis]))
    c0 = np.hstack((c, [0])) # [0] можно не преобразовывать в массив
    return np.vstack((Ab, c0[np.newaxis, :]))

<font color='red'>Тест:</font> 

In [35]:
print construct_matrix(np.array([[0, 1], [1, 2]]), np.array([8, 9]), np.array([7, 3]))

[[0 1 8]
 [1 2 9]
 [7 3 0]]


__№4__. Даны две небольшие бинарные матрицы $A$ размера $m \times n$ и $B$ размера $n \times k$. 
Написать функцию, возвращающую матрицу $C$ такую, что

$C_{ij} = \&_{s=1}^n (A_{is} \lor B_{sj})$.

Здесь $\&$ означает логическое умножение (and), а $\lor$ — дизъюнкцию (or).

In [14]:
#Пример

Example
Input:
A = [[False  True]
 [ True False]]
Input:
B = [[ True False]
 [False  True]]
Output:
[[ True False]
 [False  True]]


<font color='red'>Для решения этой задачи очень помогал доп. материал, выложенный на github. Авторское решение:</font> 

In [39]:
def perform_logical_computation(A, B):
    return np.all(np.logical_or(A[:, :, np.newaxis], B[np.newaxis, :, :]), axis=1)
    # функции np.all, np.logical_or подробно расписаны в доп. материале :)

<font color='red'>Тест:</font> 

In [41]:
A = np.array([[False, True], [True, False]])
B = np.array([[True, False], [False, True]])
print perform_logical_computation(A, B)

[[ True False]
 [False  True]]


<font color='red'>Решение через трехмерный массив полезно для того, чтоб разобраться с логическими функциями и мнимыми осями, но совершенно неэффективно по памяти. Есть другое решение, основанное на двойственности булевых законов. Если поэлементно инвертировать входные матрицы (0->1, 1->0), а затем применить законы де Моргана из дискретной математики, то можно будет воспользоваться обычным умножением матриц. __Это решение приводится для ознакомления, и от вас не требовалось__:</font> 

In [44]:
def perform_logical_computation2(A, B):
    A_ = np.logical_not(A)
    B_ = np.logical_not(B)
    return np.logical_not(A_.dot(B_) > 0)  # > 0 позволяет сопоставить натуральное число бинарному значению.

In [45]:
print perform_logical_computation2(A, B)

[[ True False]
 [False  True]]


__№5__. Напишите функцию, принимающую на вход np.array размера n и возвращающую матрицу размера n + 1 x n + 1, у которой над главной даигональю стоят элементы массива (остальные элементы должны быть нулевыми). 

In [15]:
#Пример

Example
Input:
[[1 2]]
Output:
[[0 1 0]
 [0 0 2]
 [0 0 0]]


<font color='red'>Авторское решение:</font> 

In [55]:
def make_diagonal(n):
    l = n.shape[0]
    result = np.zeros((l+1, l+1))
    result[np.arange(l), np.arange(l)+1] = n # используем индексацию
    return result

In [54]:
# Тестируем:
print make_diagonal(np.array([4, 5, 6, 7, 8]))

[[ 0.  4.  0.  0.  0.  0.]
 [ 0.  0.  5.  0.  0.  0.]
 [ 0.  0.  0.  6.  0.  0.]
 [ 0.  0.  0.  0.  7.  0.]
 [ 0.  0.  0.  0.  0.  8.]
 [ 0.  0.  0.  0.  0.  0.]]


In [56]:
# Давайте тут снова потестим функцию из №2:
print choose_elems(make_diagonal(np.array([4, 5, 6, 7, 8])), np.arange(5), np.arange(1, 6))

[ 4.  5.  6.  7.  8.]


__№6__. Дана матрица объекты-признаки X размера n x m. Посчитать (квадратную) матрицу попарных корреляций между признаками C:

$C_{ij} = cor_{ij} = \frac {cov_{ij}}{\sqrt{cov_{ii}cov_{jj}}}$ 

$cov_{ij} = cov(X_i, X_j), \quad i,j = 0, \dots, m-1.$

$cov(\{x_0, \dots, x_{n-1}\}, \{y_0, \dots, y_{n-1}\}) = \frac 1 {n-1} \sum_{i=0} ^ {n-1} (x_i-\bar x) (y_i - \bar y)$.

$\bar x = mean(\{x_0, \dots, x_{n-1}\}) = \frac 1 n \sum_{i=0} ^ {n-1} x_i$

Нельзя использовать функции np.cov, np.corrcoef, np.correlate (их можно использовать для проверки правильности ответа)


<font color='red'>Эту задачу все почему-то испугались, наверно. из-за формул. На самом деле надо сначала посчитать средние, потом матрицу ковариаций, а потом ее просто поделить на дисперсии. Авторское решение:</font>

In [142]:
def compute_corr_matrix(X):
    mean = X.mean(axis=0)[np.newaxis, :]  # на mean ограничения не было, хотя легко и без него считать среднее
    cov = (X-mean).T.dot(X-mean) / (X.shape[0]-1)  # если взглядеться в формулу, то можно увидеть обычное умножение матриц
    return cov / np.sqrt(cov.diagonal()[:, np.newaxis] * cov.diagonal()[np.newaxis, :])   # формула для корреляций

In [143]:
X = np.random.rand(100, 4)
print compute_corr_matrix(X)  # наша функция
print np.corrcoef(X.T)   # numpy-функция
print np.all(np.abs(compute_corr_matrix(X)-np.corrcoef(X.T)) < 1e-10)   # сравниваем не ==, а abs() < eps, потому что
                                                                        # числа с плавающей точкой нельзя сравнивать на равенство

[[ 1.         -0.03121313  0.05843475 -0.0480114 ]
 [-0.03121313  1.         -0.06773011 -0.03664091]
 [ 0.05843475 -0.06773011  1.         -0.00167622]
 [-0.0480114  -0.03664091 -0.00167622  1.        ]]
[[ 1.         -0.03121313  0.05843475 -0.0480114 ]
 [-0.03121313  1.         -0.06773011 -0.03664091]
 [ 0.05843475 -0.06773011  1.         -0.00167622]
 [-0.0480114  -0.03664091 -0.00167622  1.        ]]
True


__№7__. Дан массив X (размерность неизвестна). Заменить все элементы, кратные 3, которые больше 0 и меньше 100, на среднее значение по массиву.

In [19]:
#Пример

Example
Input:
[[14 11 10  0 12]
 [ 9  4 13  8  3]
 [ 6 14 13  5  5]
 [ 8  1  6  7 12]]
Output:
[[14 11 10  0  8]
 [ 8  4 13  8  8]
 [ 8 14 13  5  5]
 [ 8  1  8  7  8]]


<font color='red'>Авторское решение:</font> 

In [73]:
def find_some_elements(X):
    X[np.logical_and(np.logical_and(X > 0, X < 100), X % 3 == 0)] = X.mean()
    return X

In [75]:
# Проверка:
X = np.random.randint(300, size=20).reshape(4, 5) - 150 # генерируем случайную тестовую матрицу с отр. и пол. числами
print X
print find_some_elements(X)

[[  54  -19  -17   -1  106]
 [ -91   33  -82 -138  -22]
 [-110   94   99   91   35]
 [ 103  -34    9  -69  -49]]
[[   0  -19  -17   -1  106]
 [ -91    0  -82 -138  -22]
 [-110   94    0   91   35]
 [ 103  -34    0  -69  -49]]


In [77]:
import pandas as pd

Для выполнения заданий по pandas понадобится файл _countries.csv_: [https://goo.gl/AQqxaR](https://goo.gl/AQqxaR) --- тут его нужно скачать! Чтобы загрузить файл в jupiter, на странице с ноутбуками нажмите Upload, найдите на компьютере файл, снов анажмите upload.

<font color='red'>На всякий случай: загружать файл в jupyter нужно, только если вы выполняете ДЗ на сервере. На своем компьютере это делать не нужно. 

Для оставшихся задач почти без комментариев написаны решения, потому что проблем с ними обычно не возникало.</font> 



In [79]:
#Загрузите данные в notebook:
data = pd.read_csv("countries.csv", sep=";")
data.head()  # проверяем, что все норм прочиталось

Country  Area(sq km)  Birth rate(births/1000 population)  \
0     Afghanistan       647500                               47.02   
1        Akrotiri          123                                 NaN   
2         Albania        28748                               15.08   
3         Algeria      2381740                               17.13   
4  American Samoa          199                               23.13   

   Current account balance  Death rate(deaths/1000 population)  \
0                      NaN                               20.75   
1                      NaN                                 NaN   
2               -504000000                                5.12   
3              11900000000                                4.60   
4                      NaN                                3.33   

   Debt - external  Electricity - consumption(kWh)  \
0       8000000000                       652200000   
1              NaN                             NaN   
2       1410000000                      6760000000   
3      21900000000                     23610000000   
4              NaN                       120900000   

   Electricity - production(kWh)      Exports           GDP  \
0                      540000000    446000000  2.150000e+10   
1                            NaN          NaN           NaN   
2                     5680000000    552400000  1.746000e+10   
3                    25760000000  32160000000  2.123000e+11   
4                      130000000     30000000  5.000000e+08   

           ...           Oil - production(bbl/day)  \
0          ...                                   0   
1          ...                                 NaN   
2          ...                                2000   
3          ...                             1200000   
4          ...                                   0   

   Oil - proved reserves(bbl)  Population  Public debt(% of GDP)  \
0                           0    29928987                    NaN   
1                         NaN         NaN                    NaN   
2                   185500000     3563112                    NaN   
3                 11870000000    32531853                   37.4   
4                         NaN       57881                    NaN   

   Railways(km)  Reserves of foreign exchange & gold  \
0           NaN                                  NaN   
1           NaN                                  NaN   
2           447                           1206000000   
3          3973                          43550000000   
4           NaN                                  NaN   

   Telephones - main lines in use  Telephones - mobile cellular  \
0                           33100                         15000   
1                             NaN                           NaN   
2                          255000                       1100000   
3                         2199600                       1447310   
4                           15000                          2377   

   Total fertility rate(children born/woman)  Unemployment rate(%)  
0                                       6.75                   NaN  
1                                        NaN                   NaN  
2                                       2.04                  14.8  
3                                       1.92                  25.4  
4                                       3.25                   6.0  

[5 rows x 45 columns]

__№8__. Напишите функцию, которая берет на вход датафрейм pandas со считанными данными и возвращает ответ на следующий вопрос (строка).

Найдите страну, у которой наибольшее ВВП среди стран площадью меньше 200 или население меньше 10000 (или — не исключающее).

In [92]:
def find_country(df):
    country_idx = data.loc[(data["Area(sq km)"]<200) | (data["Population"]<1000)]["GDP"].argmax()
    return data.Country[country_idx]

In [94]:
# Проверка:
find_country(data)

'Macau'

__№9__.  Напишите функцию, которая берет на вход датафрейм pandas и возвращает датафрейм, в котором все пропуски заменены на среднее значение по столбцу. 

_Подсказка_: используйте функцию pandas.fillna()

In [97]:
def fill_na(df):
    return df.fillna(df.mean())

In [98]:
fill_na(data).head()

Country  Area(sq km)  Birth rate(births/1000 population)  \
0     Afghanistan       647500                           47.020000   
1        Akrotiri          123                           22.146667   
2         Albania        28748                           15.080000   
3         Algeria      2381740                           17.130000   
4  American Samoa          199                           23.130000   

   Current account balance  Death rate(deaths/1000 population)  \
0            -8.473897e+08                           20.750000   
1            -8.473897e+08                            9.374267   
2            -5.040000e+08                            5.120000   
3             1.190000e+10                            4.600000   
4            -8.473897e+08                            3.330000   

   Debt - external  Electricity - consumption(kWh)  \
0     8.000000e+09                    6.522000e+08   
1     6.317084e+10                    8.070919e+10   
2     1.410000e+09                    6.760000e+09   
3     2.190000e+10                    2.361000e+10   
4     6.317084e+10                    1.209000e+08   

   Electricity - production(kWh)       Exports           GDP  \
0                   5.400000e+08  4.460000e+08  2.150000e+10   
1                   8.849167e+10  4.432637e+10  2.925614e+11   
2                   5.680000e+09  5.524000e+08  1.746000e+10   
3                   2.576000e+10  3.216000e+10  2.123000e+11   
4                   1.300000e+08  3.000000e+07  5.000000e+08   

           ...           Oil - production(bbl/day)  \
0          ...                            0.000000   
1          ...                       371043.542453   
2          ...                         2000.000000   
3          ...                      1200000.000000   
4          ...                            0.000000   

   Oil - proved reserves(bbl)       Population  Public debt(% of GDP)  \
0                0.000000e+00  29928987.000000              55.896296   
1                1.416887e+10  29004941.184874              55.896296   
2                1.855000e+08   3563112.000000              55.896296   
3                1.187000e+10  32531853.000000              37.400000   
4                1.416887e+10     57881.000000              55.896296   

   Railways(km)  Reserves of foreign exchange & gold  \
0  10217.246269                         2.599825e+10   
1  10217.246269                         2.599825e+10   
2    447.000000                         1.206000e+09   
3   3973.000000                         4.355000e+10   
4  10217.246269                         2.599825e+10   

   Telephones - main lines in use  Telephones - mobile cellular  \
0                    33100.000000                  15000.000000   
1                  5998770.193966                7331345.657895   
2                   255000.000000                1100000.000000   
3                  2199600.000000                1447310.000000   
4                    15000.000000                   2377.000000   

   Total fertility rate(children born/woman)  Unemployment rate(%)  
0                                   6.750000             15.254688  
1                                   2.937778             15.254688  
2                                   2.040000             14.800000  
3                                   1.920000             25.400000  
4                                   3.250000              6.000000  

[5 rows x 45 columns]

__№10__.  Напишите функцию, которая берет на вход датафрейм pandas и число и возвращает ответ на вопрос (строка):

В какой стране ВВП (GDP) наиболее близок к указанной величине?

In [109]:
def compare_GDP(df, gdp):
    return df.Country[(df.GDP - gdp).abs().argmin()]

In [124]:
compare_GDP(data, 2.15*10**10)  # берем из таблице выше :)

'Afghanistan'

__№11__. __(Дополнительный). За выполнение этого задания можно получить +1 балл к общей сумме баллов (к 10)!__

Напишите функцию, которая берет на вход датафрейм pandas со считанными данными и возвращает датафрейм с двумя колонками: буква алфавита и значение ВВП, усреднённое по всем странам, начинающимся с данной буквы.

Для решения задачи может понадобиться функция pandas.groupby, которую вы не успели пройти на семинаре. Поэтому задача и дополнительная.

In [140]:
def compute_means_by_letters(df):   # на самом деле решение почти дано в конспекте семинара
    df2 = df[["Country", "GDP"]]
    return df2.groupby(lambda x: df2.ix[x].Country[0]).aggregate(np.mean)

In [141]:
compute_means_by_letters(data)

GDP
#  1.165000e+13
A  1.195994e+11
B  1.210610e+11
C  4.591804e+11
D  5.777075e+10
E  5.975925e+10
F  2.715113e+11
G  1.621848e+11
H  1.036600e+11
I  8.283341e+11
J  9.463075e+11
K  1.665191e+11
L  1.958222e+10
M  6.833354e+10
N  7.424858e+10
O  3.809000e+10
P  1.716514e+11
Q  1.949000e+10
R  3.986250e+11
S  1.025396e+11
T  1.354214e+11
U  2.004431e+12
V  9.387000e+10
W  9.300000e+08
Y  1.625000e+10
Z  1.688950e+10