# Отчет по выполнению домашнего задания #1

__Дата выдачи__: 28.01.2016

__Дедлайн__: 23:59 10.01.2016

__Выполнил__: Булгаков Дмитрий (ИАД16)

In [1]:
import numpy as np
import pandas as pd

__№1__.  Написать функцию, которая берет на вход прямоугольную матрицу $A$ размера m x n и превращает каждый ее столбец в дискретное распределение с помощью применения функции _softmax_:

$\text{softmax}(a_j) = \frac {\exp (a_j)}{\sum_i \exp(a_i)}$, где a --- столбец матрицы $A$.

Таким образом, в матрице, возвращенной функцией, сумма каждого столбца матрицы должна быть равна 1.

In [2]:
exmpl = np.array([[0, 1],[1, 2]])

In [3]:
def compute_softmax(A):
    tmp = np.exp(A)
    return np.divide(tmp, np.sum(tmp, axis = 0))

Проверка работы:

In [4]:
res = compute_softmax(exmpl)
print('Результат выполнения:\n', res)
print('Проверка:')
print('Сумма всех столбцов = 1: ', np.all(np.sum(res, axis = 0) == 1))
print('Нет элементов меньше 0: ', np.sum(res < 0) == 0)

Результат выполнения:
 [[ 0.26894142  0.26894142]
 [ 0.73105858  0.73105858]]
Проверка:
Сумма всех столбцов = 1:  True
Нет элементов меньше 0:  True


__№2__. Напишите функцию, принимающую на вход матрицу X и два массива i и j одинаковой длины n и возвращающую вектор np.array, состоящий из последовательности элементов [X[i[0], j[0]], X[i[1], j[1]], ..., X[i[n-1], j[n-1]]].

In [5]:
def choose_elems(X, i, j):
    if i.size * j.size != 0:
        return X[i, j]
    return X

Проверка работы:

In [6]:
exmpl = np.array([[0, 1, 2], [3, 4, 5], [6, 7 ,8]])
first_v = np.array([2, 1, 2])
second_v = np.array([0, 2, 1])
first_v = np.array([1, 2])
second_v = np.array([1, 2])
print('Исходная матрица:\n', exmpl)
print('Первый вектор: ', first_v)
print('Второй вектор: ', second_v)

Исходная матрица:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Первый вектор:  [1 2]
Второй вектор:  [1 2]


In [7]:
print('Результат выполнения: ', choose_elems(exmpl, first_v, second_v))

Результат выполнения:  [4 8]


__№3__. Написать функцию, которая берет на вход матрицу A размера m x n, вектор b длины m и вектор c длины n и возвращает матрицу, составленную из блоков:

$\begin{pmatrix} A & b \\  c^T& 0 \end{pmatrix}$ = 

$\begin{pmatrix} a_{00} & a_{01} & \dots &a_{0,n-1} & b_0 \\ 
a_{10} & a_{11} & \dots &a_{1,n-1} & b_1 \\
 &&\dots& \\
a_{m-1,0} & a_{m-1,1} & \dots &a_{m-1,n-1} & b_{m-1} \\ 
c_0 & c_1 & \dots & c_{n-1 }& 0 \end{pmatrix}$

Будем считать, что матрица A может быть очень большой, поэтому выделять дополнительную память размера, сопоставимого с размером матрицы, нельзя.

In [8]:
def construct_matrix(A, b, c):
    return np.vstack((np.column_stack((A, b)), np.append(c, 0)))

Проверка работы:

In [9]:
exmpl = np.array([[1, 2], [3, 4]])
first_v = np.array([5, 6])
second_v = np.array([1, 2])
print('Исходная матрица:\n', exmpl)
print('Первый вектор: ', first_v)
print('Второй вектор: ', second_v)

Исходная матрица:
 [[1 2]
 [3 4]]
Первый вектор:  [5 6]
Второй вектор:  [1 2]


In [10]:
print('Результат выполнения:\n', construct_matrix(exmpl, first_v, second_v))

Результат выполнения:
 [[1 2 5]
 [3 4 6]
 [1 2 0]]


__№4__. Даны две небольшие бинарные матрицы $A$ размера $m \times n$ и $B$ размера $n \times k$. 
Написать функцию, возвращающую матрицу $C$ такую, что

$C_{ij} = \&_{s=1}^n (A_{is} \lor B_{sj})$.

Здесь $\&$ означает логическое умножение (and), а $\lor$ — дизъюнкцию (or).

In [11]:
def or_diffsize_matrix(A, B):
    return np.logical_or(A[:, :, np.newaxis], B[np.newaxis, :, :])

In [12]:
def perform_logical_computation(A, B):
    return np.all(or_diffsize_matrix(A, B), axis = 1)

Проверка работы:

In [13]:
m1 = np.array([[False, True], [True, False]])
m2 = np.array([[True, False], [False, True]])
print('Матрица 1:\n', m1)
print('\nМатрица 2:\n', m2)
print('\nРезультат выполнения:\n', perform_logical_computation(m1, m2))

Матрица 1:
 [[False  True]
 [ True False]]

Матрица 2:
 [[ True False]
 [False  True]]

Результат выполнения:
 [[ True False]
 [False  True]]


__№5__. Напишите функцию, принимающую на вход np.array размера n и возвращающую матрицу размера n + 1 x n + 1, у которой над главной даигональю стоят элементы массива (остальные элементы должны быть нулевыми). 

In [14]:
def make_diagonal(n):
    if n.size == 0:
        return
    tmp = np.zeros((n.size, n.size), int)
    np.fill_diagonal(tmp, n)
    res = np.zeros((n.size + 1, n.size + 1), int)
    res[:-1,-n.size:] = tmp
    return res

Проверка работы:

In [15]:
exmpl = np.arange(1, 6)
print('Результат выполнения:\n', make_diagonal(exmpl))

Результат выполнения:
 [[0 1 0 0 0 0]
 [0 0 2 0 0 0]
 [0 0 0 3 0 0]
 [0 0 0 0 4 0]
 [0 0 0 0 0 5]
 [0 0 0 0 0 0]]


__№6__. Дана матрица объекты-признаки X размера n x m. Посчитать (квадратную) матрицу попарных корреляций между признаками C:

$C_{ij} = cor_{ij} = \frac {cov_{ij}}{\sqrt{cov_{ii}cov_{jj}}}$ 

$cov_{ij} = cov(X_i, X_j), \quad i,j = 0, \dots, m-1.$

$cov(\{x_0, \dots, x_{n-1}\}, \{y_0, \dots, y_{n-1}\}) = \frac 1 {n-1} \sum_{i=0} ^ {n-1} (x_i-\bar x) (y_i - \bar y)$.

$\bar x = mean(\{x_0, \dots, x_{n-1}\}) = \frac 1 n \sum_{i=0} ^ {n-1} x_i$

Нельзя использовать функции np.cov, np.corrcoef, np.correlate (их можно использовать для проверки правильности ответа)

In [16]:
def calc_cov(X):
    X -= X.mean(axis = 0)
    return (np.dot(X.T, X) / (X.shape[1] - 1))

In [17]:
def compute_corr_matrix(X):
    cov = calc_cov(X)
    diag = np.diag(cov)
    dmr = np.sqrt(np.multiply.outer(diag, diag))
    return cov/dmr

Проверка работы:

In [18]:
# Данные с семинара
d =  pd.read_csv("road_data.csv", sep=",", header=0, names=["cars", "accidents", "vodka", "crime", "income", "retail"])
exmpl = d.values

In [19]:
print('Результат выполнения моей ф-ии:\n', compute_corr_matrix(exmpl))
print('\nРезультат встроенной ф-ии\n', np.corrcoef(exmpl.T))

Результат выполнения моей ф-ии:
 [[ 1.          0.45343265  0.30946778  0.28711738  0.15524001  0.37982248]
 [ 0.45343265  1.          0.2818275   0.39464863 -0.12871154  0.01286648]
 [ 0.30946778  0.2818275   1.          0.57354018  0.540938    0.39909952]
 [ 0.28711738  0.39464863  0.57354018  1.          0.16912579  0.1862202 ]
 [ 0.15524001 -0.12871154  0.540938    0.16912579  1.          0.67992407]
 [ 0.37982248  0.01286648  0.39909952  0.1862202   0.67992407  1.        ]]

Результат встроенной ф-ии
 [[ 1.          0.45343265  0.30946778  0.28711738  0.15524001  0.37982248]
 [ 0.45343265  1.          0.2818275   0.39464863 -0.12871154  0.01286648]
 [ 0.30946778  0.2818275   1.          0.57354018  0.540938    0.39909952]
 [ 0.28711738  0.39464863  0.57354018  1.          0.16912579  0.1862202 ]
 [ 0.15524001 -0.12871154  0.540938    0.16912579  1.          0.67992407]
 [ 0.37982248  0.01286648  0.39909952  0.1862202   0.67992407  1.        ]]


__№7__. Дан массив X (размерность неизвестна). Заменить все элементы, кратные 3, которые больше 0 и меньше 100, на среднее значение по массиву.

In [20]:
def find_some_elements(X):
    if X.size != 0:
        X[(X % 3 == 0) & (X > 0) & (X < 100)] = np.average(X)
    return X

Проверка работы:

In [21]:
exmpl = np.array([[14, 11, 10 , 0, 12], [9, 4, 13, 8, 3], [6, 14, 13, 5, 5], [8, 1, 6, 7, 12]], dtype = float)
print('Исходная матрица:\n', exmpl)
print('Среднее значение: ', np.average(exmpl))

Исходная матрица:
 [[ 14.  11.  10.   0.  12.]
 [  9.   4.  13.   8.   3.]
 [  6.  14.  13.   5.   5.]
 [  8.   1.   6.   7.  12.]]
Среднее значение:  8.05


In [22]:
print('Результат выполнения:\n', find_some_elements(exmpl))

Результат выполнения:
 [[ 14.    11.    10.     0.     8.05]
 [  8.05   4.    13.     8.     8.05]
 [  8.05  14.    13.     5.     5.  ]
 [  8.     1.     8.05   7.     8.05]]


Загрузка данных:

In [23]:
data = pd.read_csv("countries.csv", sep=";", header=0)
data.describe()

Area(sq km)  Birth rate(births/1000 population)  \
count       263.000000                          225.000000   
mean     584987.486692                           22.146667   
std     1881415.546778                           11.126969   
min           0.000000                            7.230000   
25%         513.000000                           12.570000   
50%       48845.000000                           18.780000   
75%      333947.500000                           30.010000   
max    17075200.000000                           48.300000   

       Current account balance  Death rate(deaths/1000 population)  \
count             1.490000e+02                          225.000000   
mean             -8.473897e+08                            9.374267   
std               5.633953e+10                            4.969136   
min              -6.465000e+11                            2.300000   
25%              -5.908000e+08                            6.070000   
50%              -8.240000e+07                            8.000000   
75%               1.400000e+09                           11.260000   
max               1.702000e+11                           29.360000   

       Debt - external  Electricity - consumption(kWh)  \
count     2.010000e+02                    2.150000e+02   
mean      6.317084e+10                    8.070919e+10   
std       3.588986e+11                    3.434223e+11   
min       0.000000e+00                    1.674000e+06   
25%       6.680000e+08                    4.529000e+08   
50%       4.069000e+09                    4.450000e+09   
75%       1.707000e+10                    3.320500e+10   
max       4.710000e+12                    3.660000e+12   

       Electricity - production(kWh)       Exports           GDP  \
count                   2.130000e+02  2.240000e+02  2.300000e+02   
mean                    8.849167e+10  4.432637e+10  2.925614e+11   
std                     3.706046e+11  1.334267e+11  1.252331e+12   
min                     1.800000e+06  9.800000e+04  1.500000e+06   
25%                     4.108000e+08  2.365000e+08  2.522500e+09   
50%                     4.873000e+09  2.058000e+09  1.685500e+10   
75%                     3.551000e+10  1.624250e+10  9.183250e+10   
max                     3.839000e+12  1.109000e+12  1.175000e+13   

       GDP - per capita          ...           Oil - production(bbl/day)  \
count        230.000000          ...                          212.000000   
mean       10552.760870          ...                       371043.542453   
std        11104.610351          ...                      1190318.688954   
min          400.000000          ...                            0.000000   
25%         2000.000000          ...                            0.000000   
50%         5900.000000          ...                            0.000000   
75%        16700.000000          ...                        72145.000000   
max        58900.000000          ...                      9021000.000000   

       Oil - proved reserves(bbl)    Population  Public debt(% of GDP)  \
count                9.700000e+01  2.380000e+02             108.000000   
mean                 1.416887e+10  2.900494e+07              55.896296   
std                  3.923463e+10  1.175456e+08              36.954000   
min                  0.000000e+00  4.600000e+01               2.100000   
25%                  8.000000e+07  2.837770e+05              31.475000   
50%                  4.088000e+08  4.440570e+06              50.750000   
75%                  4.408000e+09  1.628023e+07              69.675000   
max                  2.617000e+11  1.306314e+09             228.300000   

        Railways(km)  Reserves of foreign exchange & gold  \
count     134.000000                         1.470000e+02   
mean    10217.246269                         2.599825e+10   
std     29857.440213                         8.023959e+10   
min         6.000000                         2.978000e+07   
25%       801.250000        

__№8__. Напишите функцию, которая берет на вход датафрейм pandas со считанными данными и возвращает ответ на следующий вопрос (строка).

Найдите страну, у которой наибольшее ВВП среди стран площадью меньше 200 или население меньше 10000 (или — не исключающее).

In [24]:
def find_country(df): 
    t = df.loc[(df['Area(sq km)'] < 200) | (df['Population'] < 10000)]
    t2 = t['GDP'].max()
    return t.loc[t['GDP'] == t2]

Проверка работы

In [25]:
find_country(data)

Country  Area(sq km)  Birth rate(births/1000 population)  \
145   Macau           25                                8.04   

     Current account balance  Death rate(deaths/1000 population)  \
145                      NaN                                4.23   

     Debt - external  Electricity - consumption(kWh)  \
145       2700000000                      1772000000   

     Electricity - production(kWh)     Exports         GDP  \
145                     1719000000  2580000000  9100000000   

             ...           Oil - production(bbl/day)  \
145          ...                                   0   

     Oil - proved reserves(bbl)  Population  Public debt(% of GDP)  \
145                         NaN      449198                    NaN   

     Railways(km)  Reserves of foreign exchange & gold  \
145           NaN                                  NaN   

     Telephones - main lines in use  Telephones - mobile cellular  \
145                          174600                        364000   

     Total fertility rate(children born/woman)  Unemployment rate(%)  
145                                       0.93                   4.7  

[1 rows x 45 columns]

С другой стороны, 

In [26]:
data.loc[(data['Area(sq km)'] < 200) | (data['Population'] < 10000)].sort_values(by="GDP", ascending=False).head()

Country  Area(sq km)  Birth rate(births/1000 population)  \
145                   Macau           25                                8.04   
124                  Jersey          116                                9.66   
101                Guernsey           78                                9.01   
35   British Virgin Islands          153                               14.96   
27                  Bermuda           53                               11.60   

     Current account balance  Death rate(deaths/1000 population)  \
145                      NaN                                4.23   
124                      NaN                                9.19   
101                      NaN                                9.95   
35                       NaN                                4.42   
27                       NaN                                7.63   

     Debt - external  Electricity - consumption(kWh)  \
145       2700000000                      1772000000   
124              NaN                       630100000   
101              NaN                             NaN   
35          36100000                        33740000   
27         160000000                       598000000   

     Electricity - production(kWh)     Exports         GDP  \
145                     1719000000  2580000000  9100000000   
124                            NaN         NaN  3600000000   
101                            NaN         NaN  2590000000   
35                        36280000    25300000  2498000000   
27                       643000000   879000000  2330000000   

             ...           Oil - production(bbl/day)  \
145          ...                                   0   
124          ...                                 NaN   
101          ...                                 NaN   
35           ...                                   0   
27           ...                                   0   

     Oil - proved reserves(bbl)  Population  Public debt(% of GDP)  \
145                         NaN      449198                    NaN   
124                         NaN       90812                    NaN   
101                         NaN       65228                    NaN   
35                          NaN       22643                    NaN   
27                          NaN       65365                    NaN   

     Railways(km)  Reserves of foreign exchange & gold  \
145           NaN                                  NaN   
124           NaN                                  NaN   
101           NaN                                  NaN   
35            NaN                                  NaN   
27            NaN                                  NaN   

     Telephones - main lines in use  Telephones - mobile cellular  \
145                          174600                        364000   
124                           73900                         61400   
101                           55000                         31500   
35                            11700                          8000   
27                            56000                         37873   

     Total fertility rate(children born/woman)  Unemployment rate(%)  
145                                       0.93                   4.7  
124                                       1.57                   0.9  
101                                       1.38                   0.5  
35                                        1.72                   3.0  
27                                        1.89                   5.0  

[5 rows x 45 columns]

__№9__.  Напишите функцию, которая берет на вход датафрейм pandas и возвращает датафрейм, в котором все пропуски заменены на среднее значение по столбцу. 

_Подсказка_: используйте функцию pandas.fillna()

In [27]:
def fill_na(df):
    return df.fillna(df.mean())

Проверка работы:

In [28]:
fill_na(data).head()

Country  Area(sq km)  Birth rate(births/1000 population)  \
0     Afghanistan       647500                           47.020000   
1        Akrotiri          123                           22.146667   
2         Albania        28748                           15.080000   
3         Algeria      2381740                           17.130000   
4  American Samoa          199                           23.130000   

   Current account balance  Death rate(deaths/1000 population)  \
0            -8.473897e+08                           20.750000   
1            -8.473897e+08                            9.374267   
2            -5.040000e+08                            5.120000   
3             1.190000e+10                            4.600000   
4            -8.473897e+08                            3.330000   

   Debt - external  Electricity - consumption(kWh)  \
0     8.000000e+09                    6.522000e+08   
1     6.317084e+10                    8.070919e+10   
2     1.410000e+09                    6.760000e+09   
3     2.190000e+10                    2.361000e+10   
4     6.317084e+10                    1.209000e+08   

   Electricity - production(kWh)       Exports           GDP  \
0                   5.400000e+08  4.460000e+08  2.150000e+10   
1                   8.849167e+10  4.432637e+10  2.925614e+11   
2                   5.680000e+09  5.524000e+08  1.746000e+10   
3                   2.576000e+10  3.216000e+10  2.123000e+11   
4                   1.300000e+08  3.000000e+07  5.000000e+08   

           ...           Oil - production(bbl/day)  \
0          ...                            0.000000   
1          ...                       371043.542453   
2          ...                         2000.000000   
3          ...                      1200000.000000   
4          ...                            0.000000   

   Oil - proved reserves(bbl)       Population  Public debt(% of GDP)  \
0                0.000000e+00  29928987.000000              55.896296   
1                1.416887e+10  29004941.184874              55.896296   
2                1.855000e+08   3563112.000000              55.896296   
3                1.187000e+10  32531853.000000              37.400000   
4                1.416887e+10     57881.000000              55.896296   

   Railways(km)  Reserves of foreign exchange & gold  \
0  10217.246269                         2.599825e+10   
1  10217.246269                         2.599825e+10   
2    447.000000                         1.206000e+09   
3   3973.000000                         4.355000e+10   
4  10217.246269                         2.599825e+10   

   Telephones - main lines in use  Telephones - mobile cellular  \
0                    33100.000000                  15000.000000   
1                  5998770.193966                7331345.657895   
2                   255000.000000                1100000.000000   
3                  2199600.000000                1447310.000000   
4                    15000.000000                   2377.000000   

   Total fertility rate(children born/woman)  Unemployment rate(%)  
0                                   6.750000             15.254688  
1                                   2.937778             15.254688  
2                                   2.040000             14.800000  
3                                   1.920000             25.400000  
4                                   3.250000              6.000000  

[5 rows x 45 columns]

Средние значения: 

In [29]:
data.mean().head()

Area(sq km)                           5.849875e+05
Birth rate(births/1000 population)    2.214667e+01
Current account balance              -8.473897e+08
Death rate(deaths/1000 population)    9.374267e+00
Debt - external                       6.317084e+10
dtype: float64

__№10__.  Напишите функцию, которая берет на вход датафрейм pandas и число и возвращает ответ на вопрос (строка):

В какой стране ВВП (GDP) наиболее близок к указанной величине?

In [30]:
def compare_GDP(df, gdp):
    delta = abs(gdp - df['GDP'])
    return df.loc[delta == min(delta)]

Проверка работы:

In [31]:
exmpl = 499999999
compare_GDP(data, exmpl)

Country  Area(sq km)  Birth rate(births/1000 population)  \
4  American Samoa          199                               23.13   

   Current account balance  Death rate(deaths/1000 population)  \
4                      NaN                                3.33   

   Debt - external  Electricity - consumption(kWh)  \
4              NaN                       120900000   

   Electricity - production(kWh)   Exports        GDP          ...           \
4                      130000000  30000000  500000000          ...            

   Oil - production(bbl/day)  Oil - proved reserves(bbl)  Population  \
4                          0                         NaN       57881   

   Public debt(% of GDP)  Railways(km)  Reserves of foreign exchange & gold  \
4                    NaN           NaN                                  NaN   

   Telephones - main lines in use  Telephones - mobile cellular  \
4                           15000                          2377   

   Total fertility rate(children born/woman)  Unemployment rate(%)  
4                                       3.25                     6  

[1 rows x 45 columns]

__№11__. __(Дополнительный). За выполнение этого задания можно получить +1 балл к общей сумме баллов (к 10)!__

Напишите функцию, которая берет на вход датафрейм pandas со считанными данными и возвращает датафрейм с двумя колонками: буква алфавита и значение ВВП, усреднённое по всем странам, начинающимся с данной буквы.

Для решения задачи может понадобиться функция pandas.groupby, которую вы не успели пройти на семинаре. Поэтому задача и дополнительная.

In [32]:
def compute_means_by_letters(df):
    t = df[['Country', 'GDP']]
    d = t.groupby(t['Country'].str[:1])
    return d.mean()

Проверка работы:

In [33]:
compute_means_by_letters(data)

GDP
Country              
#        1.165000e+13
A        1.195994e+11
B        1.210610e+11
C        4.591804e+11
D        5.777075e+10
E        5.975925e+10
F        2.715113e+11
G        1.621848e+11
H        1.036600e+11
I        8.283341e+11
J        9.463075e+11
K        1.665191e+11
L        1.958222e+10
M        6.833354e+10
N        7.424858e+10
O        3.809000e+10
P        1.716514e+11
Q        1.949000e+10
R        3.986250e+11
S        1.025396e+11
T        1.354214e+11
U        2.004431e+12
V        9.387000e+10
W        9.300000e+08
Y        1.625000e+10
Z        1.688950e+10