# Отчет по выполнению домашнего задания #1

__Дата выдачи__: 28.01.2016

__Дедлайн__: 23:59 10.01.2016

__Выполнил__: Булгаков Дмитрий (ИАД16)

In [1]:
import numpy as np

__№1__.  Написать функцию, которая берет на вход прямоугольную матрицу $A$ размера m x n и превращает каждый ее столбец в дискретное распределение с помощью применения функции _softmax_:

$\text{softmax}(a_j) = \frac {\exp (a_j)}{\sum_i \exp(a_i)}$, где a --- столбец матрицы $A$.

Таким образом, в матрице, возвращенной функцией, сумма каждого столбца матрицы должна быть равна 1.

In [2]:
exmpl = np.array([[0, 1],[1, 2]])

In [3]:
def compute_softmax(A):
    tmp = np.exp(A)
    return np.divide(tmp, np.sum(tmp, axis = 0))

Проверка работы:

In [4]:
res = compute_softmax(exmpl)
print('Результат выполнения:\n', res)
print('Проверка:')
print('Сумма всех столбцов = 1: ', np.all(np.sum(res, axis = 0) == 1))
print('Нет элементов меньше 0: ', np.sum(res < 0) == 0)

Результат выполнения:
 [[ 0.26894142  0.26894142]
 [ 0.73105858  0.73105858]]
Проверка:
Сумма всех столбцов = 1:  True
Нет элементов меньше 0:  True


__№2__. Напишите функцию, принимающую на вход матрицу X и два массива i и j одинаковой длины n и возвращающую вектор np.array, состоящий из последовательности элементов [X[i[0], j[0]], X[i[1], j[1]], ..., X[i[n-1], j[n-1]]].

In [5]:
def choose_elems(X, i, j):
    if i.size * j.size != 0:
        return X[i, j]
    return X

Проверка работы:

In [6]:
exmpl = np.array([[0, 1, 2], [3, 4, 5], [6, 7 ,8]])
first_v = np.array([2, 1, 2])
second_v = np.array([0, 2, 1])
first_v = np.array([1, 2])
second_v = np.array([1, 2])
print('Исходная матрица:\n', exmpl)
print('Первый вектор: ', first_v)
print('Второй вектор: ', second_v)

Исходная матрица:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Первый вектор:  [1 2]
Второй вектор:  [1 2]


In [7]:
print('Результат выполнения: ', choose_elems(exmpl, first_v, second_v))

Результат выполнения:  [4 8]


__№3__. Написать функцию, которая берет на вход матрицу A размера m x n, вектор b длины m и вектор c длины n и возвращает матрицу, составленную из блоков:

$\begin{pmatrix} A & b \\  c^T& 0 \end{pmatrix}$ = 

$\begin{pmatrix} a_{00} & a_{01} & \dots &a_{0,n-1} & b_0 \\ 
a_{10} & a_{11} & \dots &a_{1,n-1} & b_1 \\
 &&\dots& \\
a_{m-1,0} & a_{m-1,1} & \dots &a_{m-1,n-1} & b_{m-1} \\ 
c_0 & c_1 & \dots & c_{n-1 }& 0 \end{pmatrix}$

Будем считать, что матрица A может быть очень большой, поэтому выделять дополнительную память размера, сопоставимого с размером матрицы, нельзя.

In [8]:
def construct_matrix(A, b, c):
    return np.vstack((np.column_stack((A, b)), np.append(c, 0)))

Проверка работы:

In [9]:
exmpl = np.array([[1, 2], [3, 4]])
first_v = np.array([5, 6])
second_v = np.array([1, 2])
print('Исходная матрица:\n', exmpl)
print('Первый вектор: ', first_v)
print('Второй вектор: ', second_v)

Исходная матрица:
 [[1 2]
 [3 4]]
Первый вектор:  [5 6]
Второй вектор:  [1 2]


In [10]:
print('Результат выполнения:\n', construct_matrix(exmpl, first_v, second_v))

Результат выполнения:
 [[1 2 5]
 [3 4 6]
 [1 2 0]]


__№4__. Даны две небольшие бинарные матрицы $A$ размера $m \times n$ и $B$ размера $n \times k$. 
Написать функцию, возвращающую матрицу $C$ такую, что

$C_{ij} = \&_{s=1}^n (A_{is} \lor B_{sj})$.

Здесь $\&$ означает логическое умножение (and), а $\lor$ — дизъюнкцию (or).

__№5__. Напишите функцию, принимающую на вход np.array размера n и возвращающую матрицу размера n + 1 x n + 1, у которой над главной даигональю стоят элементы массива (остальные элементы должны быть нулевыми). 

In [11]:
def above_diagonal(V):
    if V.size == 0:
        return
    tmp = np.zeros((V.size, V.size), int)
    np.fill_diagonal(tmp, V)
    res = np.zeros((V.size + 1, V.size + 1), int)
    res[:-1,-V.size:] = tmp
    return res

Проверка работы:

In [12]:
exmpl = np.arange(1, 6)
print('Результат выполнения:\n', above_diagonal(exmpl))

Результат выполнения:
 [[0 1 0 0 0 0]
 [0 0 2 0 0 0]
 [0 0 0 3 0 0]
 [0 0 0 0 4 0]
 [0 0 0 0 0 5]
 [0 0 0 0 0 0]]


__№6__. Дана матрица объекты-признаки X размера n x m. Посчитать (квадратную) матрицу попарных корреляций между признаками C:

$C_{ij} = cor_{ij} = \frac {cov_{ij}}{\sqrt{cov_{ii}cov_{jj}}}$ 

$cov_{ij} = cov(X_i, X_j), \quad i,j = 0, \dots, m-1.$

$cov(\{x_0, \dots, x_{n-1}\}, \{y_0, \dots, y_{n-1}\}) = \frac 1 {n-1} \sum_{i=0} ^ {n-1} (x_i-\bar x) (y_i - \bar y)$.

$\bar x = mean(\{x_0, \dots, x_{n-1}\}) = \frac 1 n \sum_{i=0} ^ {n-1} x_i$

Нельзя использовать функции np.cov, np.corrcoef, np.correlate (их можно использовать для проверки правильности ответа)

__№7__. Дан массив X (размерность неизвестна). Заменить все элементы, кратные 3, которые больше 0 и меньше 100, на среднее значение по массиву.

In [13]:
def find_el_by_condition(A):
    if A.size != 0:
        A[(A % 3 == 0) & (A > 0) & (A < 100)] = np.average(A)
    return A

Проверка работы:

In [14]:
exmpl = np.array([[14, 11, 10 , 0, 12], [9, 4, 13, 8, 3], [6, 14, 13, 5, 5], [8, 1, 6, 7, 12]], dtype = float)
print('Исходная матрица:\n', exmpl)
print('Среднее значение: ', np.average(exmpl))

Исходная матрица:
 [[ 14.  11.  10.   0.  12.]
 [  9.   4.  13.   8.   3.]
 [  6.  14.  13.   5.   5.]
 [  8.   1.   6.   7.  12.]]
Среднее значение:  8.05


In [15]:
print('Результат выполнения:\n', find_el_by_condition(exmpl))

Результат выполнения:
 [[ 14.    11.    10.     0.     8.05]
 [  8.05   4.    13.     8.     8.05]
 [  8.05  14.    13.     5.     5.  ]
 [  8.     1.     8.05   7.     8.05]]


__№8__. Напишите функцию, которая берет на вход датафрейм pandas со считанными данными и возвращает ответ на следующий вопрос (строка).

Найдите страну, у которой наибольшее ВВП среди стран площадью меньше 200 или население меньше 10000 (или — не исключающее).