### Task #1
Написать функцию, которая принимает на вход целочисленный массив и возвращает его максимальный четный элемент.
Подключаю numpy, который крут и офигенен и вообще.

In [8]:
import numpy as np

Создаю массив из библиотеки NumPy, преобразовав обычный.

In [9]:
a = [1, 2, 3, 3, 4, 4, 4, 5, 5, 5, 10005000]
a = np.array(a)

Теперь пишу функцию, которая будет искать максимальное число среди четных в массиве. Все четные элементы можно найти 
как a[a % 2 == 0]. И потом добавить .max(), чтобы найти максимальный элемент.

In [10]:
def findEvenMaximum(inputArray):
    return inputArray[inputArray % 2 == 0].max()

Вы восхитительны! Проверяю на работоспособноость сие счастье.

In [11]:
findEvenMaximum(a)

10005000

Все вегно :)

### Task #2
Дана матрица n x d, где n - число объектов, d - число признаков. Подсчитать выборочное среднее μ 
и выборочную ковариационную матрицу K без использования стандартных функций np.mean, np.cov

Для начала, создам матрицу. Снова из библиотеки NumPy.

In [14]:
matrix = [[1, 2, 3, 4], [5, 6, 7, 8], [1, 2, 3, 4]]
matrix = np.array(matrix)

Идеально. Теперь Считаю сумму всего этого.

In [15]:
np.sum(matrix)

46

А вот так можно посчитать количество элентов.

In [16]:
np.size(matrix)

12

Усё працюе. Оформляю все в виде функции.

In [17]:
def computeMean(inputMatrix):
    return np.sum(inputMatrix) / np.size(inputMatrix)

Вроде, верно. Сравниваю результаты со стандартной функцией.

In [18]:
print('Наш метод: ', computeMean(matrix))
print('Встроенная ф-я: ', np.mean(matrix))

Наш метод:  3.83333333333
Встроенная ф-я:  3.83333333333


Половина сделана. Идем дальше.

Теперь для ковариации. Посчитать сумму (элемент - н) можно вот так np.sum(array - n). Тогда ф-я будет иметь вид:

In [19]:
def computeCov(inputMatrix):
    mean = computeMean(matrix)
    return np.sum( (inputMatrix - mean) ** 2) / (np.size(inputMatrix) - 1) #хз как делать

Все стандартно по формуле. 

In [20]:
print('Наш метод: ', computeCov(matrix))
print('Встроенная ф-я: ', np.cov(matrix))

Наш метод:  5.24242424242
Встроенная ф-я:  [[ 1.66666667  1.66666667  1.66666667]
 [ 1.66666667  1.66666667  1.66666667]
 [ 1.66666667  1.66666667  1.66666667]]


### Task #3
Посчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.
Для Х = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])

Собственно, для начала, создаю такую матрицу.

In [21]:
x = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
x

array([[1, 0, 1],
       [2, 0, 2],
       [3, 0, 3],
       [4, 4, 4]])

Элементы по диагонали можно получить как x.diagonal()

In [22]:
x.diagonal()

array([1, 0, 3])

Из них выбираю все отличные от 0. делается это x[x.nonzero()].

*Тут будет не для диагональных элементов, а для всех.

In [23]:
x[x.nonzero()]

array([1, 1, 2, 2, 3, 3, 4, 4, 4])

Ну, все уже пройдено. Можно оформлять в виде ф-ии. Поизведение найду через np.prod()

In [24]:
def multiplyDiagonal(inputMatrix):
    tmp = inputMatrix.diagonal()
    tmp = tmp[tmp.nonzero()]
    return np.prod(tmp)

In [25]:
multiplyDiagonal(x)

3

Ответ совпадает с таковым в условии:)

### Task #4
При помощи метода Монте-Карло по 10000 точек приближенно вычислить значение интеграла
intergal cos(x^2)dx from 0 to 0.5

Я хз что такое метод Монте - Карло. Пытался понять тут. Скорее всего, верно.
https://helloacm.com/how-to-compute-numerical-integration-in-numpy-python/

Насколько я понял, просто считаем площадь по прямоугольникам, точность, естественно, зависит от их количества.

Т.е нужно разбить промежуток от a до b на n точек и посчитать площадь. Разбить отрезок на n точек можно вот так:

In [26]:
a = 0
b = 0.5
n = 10000
dotslinspace = np.linspace(a, b, n)
dotslinspace

array([  0.00000000e+00,   5.00050005e-05,   1.00010001e-04, ...,
         4.99899990e-01,   4.99949995e-01,   5.00000000e-01])

Далее, надо научиться брать от каждого элемента из этого линспейса ф-ю. // применять ф-ю с аргументом = каждый из линспейса: 

Хз, можно ли это сделать правильней. Но я оформлю это в виде отдельной ф-ии: (то, что cos(x^2))

In [27]:
def calcCosx2(x):
    return np.cos(x ** 2)

Тогда, применить для каждого элемента:

In [28]:
calcCosx2(dotslinspace)

array([ 1.        ,  1.        ,  1.        , ...,  0.96893716,
        0.96892479,  0.96891242])

Собственно, все что нужно для написания ф-ии по приближенному вычислению интеграла есть. Это будет как то так: 

In [29]:
def integrateMC(function, a, b, ndots):
    arg_linspace = np.linspace(a, b, ndots)
    fx = function(arg_linspace) #считаю значения ф-ии в каждой точке; высота прямоугольника, если делить график ф-ии
    # тогда площадь прямоугольника = основание * высоту. основание каждого будет (b - a) / n
    return np.sum(fx) * (b - a) / n

Ну все, проверяем работу:

In [30]:
print('Площадь по методу Монте-Карло: ', integrateMC(calcCosx2, a, b, n))

Площадь по методу Монте-Карло:  0.496883563571


Результат совпадает с wolframalpha. Идем дальше c:

### Task #5
Найти максимальный элемент в векторе х среди элементов, перед которыми стоит нулевой.
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]). Ответ: 5.

In [31]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
tmp = np.max(x[np.nonzero(x)])
tmp

хз чет

SyntaxError: invalid syntax (<ipython-input-31-43bff76b9a56>, line 5)

### Task #6
Пусть Х - случайная величина, имеющая распределение Пуассона с параметром λ = 5
P(x = k) = (5 ^ k) / k! * e ^ (-5)

Собственно попробую методом лома: (нужна библиотека scipy)

In [120]:
from scipy.special import factorial

Теперь, собственно, ф - я.

In [121]:
def computePoisson(ld, k):
    return ((ld ** k) / factorial(k)) * np.exp(-k)

In [140]:
p = np.arange(50)

In [141]:
p

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [147]:
computePoisson(5, 50)

5.6325006325190829e-52