### Task #1
Написать функцию, которая принимает на вход целочисленный массив и возвращает его максимальный четный элемент.
Подключаю numpy, который крут и офигенен и вообще.

In [2]:
import numpy as np

Создаю массив из библиотеки NumPy, преобразовав обычный.

In [3]:
a = [1, 2, 3, 3, 4, 4, 4, 5, 5, 5, 10005000]
a = np.array(a)

Теперь пишу функцию, которая будет искать максимальное число среди четных в массиве. Все четные элементы можно найти 
как a[a % 2 == 0]. И потом добавить .max(), чтобы найти максимальный элемент.

In [4]:
def findEvenMaximum(inputArray):
    return inputArray[inputArray % 2 == 0].max()

Вы восхитительны! Проверяю на работоспособноость сие счастье.

In [5]:
findEvenMaximum(a)

10005000

Все вегно :)

### Task #2
Дана матрица n x d, где n - число объектов, d - число признаков. Подсчитать выборочное среднее μ 
и выборочную ковариационную матрицу K без использования стандартных функций np.mean, np.cov

Для начала, создам матрицу. Снова из библиотеки NumPy.

In [46]:
matrix = [[1, 2, 3, 4], [5, 6, 7, 8], [1, 2, 3, 4]]
matrix = np.array(matrix)

Идеально. Теперь Считаю сумму всего этого.

In [7]:
np.sum(matrix)

46

А вот так можно посчитать количество элентов.

In [8]:
np.size(matrix)

12

Усё працюе. Оформляю все в виде функции.

In [9]:
def computeMean(inputMatrix):
    return np.sum(inputMatrix) / np.size(inputMatrix)

Вроде, верно. Сравниваю результаты со стандартной функцией.

In [10]:
print('Наш метод: ', computeMean(matrix))
print('Встроенная ф-я: ', np.mean(matrix))

Наш метод:  3.83333333333
Встроенная ф-я:  3.83333333333


Половина сделана. Идем дальше.

Теперь для ковариации. Посчитать сумму (элемент - н) можно вот так np.sum(array - n). Тогда ф-я будет иметь вид:

In [11]:
def computeCov(inputMatrix):
    mean = computeMean(matrix)
    return np.sum( (inputMatrix - mean) ** 2) / (np.size(inputMatrix) - 1) #хз как делать

Все стандартно по формуле. 

In [12]:
print('Наш метод: ', computeCov(matrix))
print('Встроенная ф-я: ', np.cov(matrix))

Наш метод:  5.24242424242
Встроенная ф-я:  [[ 1.66666667  1.66666667  1.66666667]
 [ 1.66666667  1.66666667  1.66666667]
 [ 1.66666667  1.66666667  1.66666667]]


### Task #3
Посчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.
Для Х = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])

Собственно, для начала, создаю такую матрицу.

In [13]:
x = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
x

array([[1, 0, 1],
       [2, 0, 2],
       [3, 0, 3],
       [4, 4, 4]])

Элементы по диагонали можно получить как x.diagonal()

In [14]:
x.diagonal()

array([1, 0, 3])

Из них выбираю все отличные от 0. делается это x[x.nonzero()].

*Тут будет не для диагональных элементов, а для всех.

In [15]:
x[x.nonzero()]

array([1, 1, 2, 2, 3, 3, 4, 4, 4])

Ну, все уже пройдено. Можно оформлять в виде ф-ии. Поизведение найду через np.prod()

In [16]:
def multiplyDiagonal(inputMatrix):
    tmp = inputMatrix.diagonal()
    tmp = tmp[tmp.nonzero()]
    return np.prod(tmp)

In [17]:
multiplyDiagonal(x)

3

Ответ совпадает с таковым в условии:)

### Task #4
При помощи метода Монте-Карло по 10000 точек приближенно вычислить значение интеграла
intergal cos(x^2)dx from 0 to 0.5

Я хз что такое метод Монте - Карло. Пытался понять тут. Скорее всего, верно.
https://helloacm.com/how-to-compute-numerical-integration-in-numpy-python/

Насколько я понял, просто считаем площадь по прямоугольникам, точность, естественно, зависит от их количества.

Т.е нужно разбить промежуток от a до b на n точек и посчитать площадь. Разбить отрезок на n точек можно вот так:

In [18]:
a = 0
b = 0.5
n = 10000
dotslinspace = np.linspace(a, b, n)
dotslinspace

array([  0.00000000e+00,   5.00050005e-05,   1.00010001e-04, ...,
         4.99899990e-01,   4.99949995e-01,   5.00000000e-01])

Далее, надо научиться брать от каждого элемента из этого линспейса ф-ю. // применять ф-ю с аргументом = каждый из линспейса: 

Хз, можно ли это сделать правильней. Но я оформлю это в виде отдельной ф-ии: (то, что cos(x^2))

In [19]:
def calcCosx2(x):
    return np.cos(x ** 2)

Тогда, применить для каждого элемента:

In [20]:
calcCosx2(dotslinspace)

array([ 1.        ,  1.        ,  1.        , ...,  0.96893716,
        0.96892479,  0.96891242])

Собственно, все что нужно для написания ф-ии по приближенному вычислению интеграла есть. Это будет как то так: 

In [21]:
def integrateMC(function, a, b, ndots):
    arg_linspace = np.linspace(a, b, ndots)
    fx = function(arg_linspace) #считаю значения ф-ии в каждой точке; высота прямоугольника, если делить график ф-ии
    # тогда площадь прямоугольника = основание * высоту. основание каждого будет (b - a) / n
    return np.sum(fx) * (b - a) / n

Ну все, проверяем работу:

In [22]:
print('Площадь по методу Монте-Карло: ', integrateMC(calcCosx2, a, b, n))

Площадь по методу Монте-Карло:  0.496883563571


Результат совпадает с wolframalpha. Идем дальше c:

### Task #5
Найти максимальный элемент в векторе х среди элементов, перед которыми стоит нулевой.
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]). Ответ: 5.

Для начала, найду индексы нулевых элементов. Это делается так:

In [41]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
zero_indexes_arr = np.where(x == 0)

(array([2, 4, 5, 8], dtype=int64),)

Но мне такое не сильно нужно на самом деле. Мне нужны индексы элементов после 0. Сказано - сделано.

In [48]:
next_to_zero_index = np.where(x == 0)
next_to_zero_index = np.array(next_to_zero_index) + 1
next_to_zero_index

array([[3, 5, 6, 9]], dtype=int64)

Ну, и, собственно, полученная ф-я:

In [62]:
def maxNexToZero(inputArray):
    tmp = np.array(np.where(x == 0)) + 1
    return inputArray[tmp[tmp < inputArray.size]].max()

In [65]:
print('А вот и наш ответ, детишки: ', maxNexToZero(x))

А вот и наш ответ, детишки:  5


### Task #6
Пусть Х - случайная величина, имеющая распределение Пуассона с параметром λ = 5
P(x = k) = (5 ^ k) / k! * e ^ (-5)

Собственно попробую методом лома: (нужна библиотека scipy)

In [24]:
from scipy.special import factorial

Теперь, собственно, ф - я.

In [25]:
def computePoisson(ld, k):
    return ((ld ** k) / factorial(k)) * np.exp(-k)

In [36]:
p_size = 50
p = np.arange(p_size)
p

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

Для одного элемента так будет работать, для вектора - нет. (Если тебе так интересно, мой юный друг, можешь проверить лично)

In [37]:
lamda = 5
computePoisson(lamda, 49)

1.5310724118160698e-50

А я уже ненавижу это задание. Но продолжаем. Чтобы все было кошерно нужно векторизировать ф-ю. 

In [43]:
vectorComputePoisson = np.vectorize(computePoisson)
t = vectorComputePoisson(lamda, p)
print('Наш массив, тадамс:\n',t)

Наш массив, тадамс:
 [  1.00000000e+00   1.83939721e+00   1.69169104e+00   1.03723059e+00
   4.76969763e-01   1.75467370e-01   5.37923649e-02   1.41350751e-02
   3.25000221e-03   6.64227220e-04   1.22177769e-04   2.04303134e-05
   3.13162178e-06   4.43099720e-07   5.82168847e-08   7.13893167e-09
   8.20708186e-10   8.88004908e-11   9.07440970e-12   8.78497045e-13
   8.07952505e-14   7.07688371e-15   5.91690915e-16   4.73197659e-17
   3.62666022e-18   2.66834747e-19   1.88775034e-20   1.28604544e-21
   8.44838712e-23   5.35859988e-24   3.28553122e-25   1.94948288e-26
   1.12058543e-27   6.24606578e-29   3.37911645e-30   1.77586782e-31
   9.07368417e-33   4.51084035e-34   2.18348083e-35   1.02981757e-36
   4.73560891e-38   2.12455263e-39   9.30451471e-41   3.98016241e-42
   1.66388628e-43   6.80121726e-45   2.71959566e-46   1.06434397e-47
   4.07864859e-49   1.53107241e-50]


That's all, folks!